spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/config
          search-locations: file:///C:/Users/jalit/OneDrive/Desktop/microservice/section%202/section%206/v2-spring-cloud-config/config/

server:
  port: 8071