services:
  accounts:
    image: "jalithakheminda/accounts:s4"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "700m"
    networks:
      - jalitha-network

  cards:
    image: "jalithakheminda/cards:s4"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "700m"
    networks:
      - jalitha-network

  loans:
    image: "jalithakheminda/loans:s4"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "700m"
    networks:
      - jalitha-network

networks:
  jalitha-network:
    driver: bridge  # bridge means it will create a new network